### ISSUE TITLE
Navbar Redesign.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#1]
Must look similar to a mobile app's navbar instead of being a web page's navbar. 
Example: Gmail's navbar.

**Comment by daptheHuman** [comment]
did you mean the hamburger navbar? like this?
![image](https://user-images.githubusercontent.com/32587372/135720202-3e88e784-183c-4b2d-8957-0dd8d130298a.png)

**Comment by Abhiramborige** [comment]
@daptheHuman 
No no. I didn't mean that hamburger. I mean that current navbar is toggling upwards down and vice versa. Gmail's navbar opens from left to right and covers the whole page. Could you please do that.

**Comment by daptheHuman** [comment]
> @daptheHuman No no. I didn't mean that hamburger. I mean that current navbar is toggling upwards down and vice versa. Gmail's navbar opens from left to right and covers the whole page. Could you please do that.

I still don't get what you mention about can you give me a photo or a video/gif about that?

**Comment by Abhiramborige** [comment]
Go to https://developers.google.com/, see in mobile version of the website, the hamburger will be top left and by clicking, navbar will toggle. This is similar to gmail's navbar. Hope you get it.
That must be only when display is in mobile, else the same as current will be fine.

**Comment by daptheHuman** [comment]
ok just give me a try

**Comment by SoundaryaKhanapur** [comment]
Hello I'd like to pick this up as i have recently worked on this a lot

**Comment by Abhiramborige** [comment]
> ok just give me a try

Dude, just awesome one.
Could you please fix some issues with it. (only if you are interested, else leave it no worries)
1. Inside nav tag with class="navbar", dont make the div with class="brand-title" to display=none when media query fires.
2. When in mobile view, put the "Ithihaas" anchor tag to the right of div, so that hamburger will not get over it.
3. Please do 1 step because when switching to light mode, hamburger is getting invisible
4. make the hamburger into "X" symbol when navigation is open and revert it back when closed (optional)

**Comment by Abhiramborige** [comment]
> Hello I'd like to pick this up as i have recently worked on this a lot

Dude, you can stop working on this.
You can make the changes that I have mentioned if interested.

**Comment by Abhiramborige** [comment]
> > ok just give me a try
> 
> Dude, just awesome one. Could you please fix some issues with it. (only if you are interested, else leave it no worries)
> 
> 1. Inside nav tag with class="navbar", dont make the div with class="brand-title" to display=none when media query fires.
> 2. When in mobile view, put the "Ithihaas" anchor tag to the right of div, so that hamburger will not get over it.
> 3. Please do 1 step because when switching to light mode, hamburger is getting invisible
> 4. make the hamburger into "X" symbol when navigation is open and revert it back when closed (optional)

dude, dont do step 1, i got it why you did like that, that's actually great.
instead of 3, make the hamburger span elements to black when theme is switched

**Comment by daptheHuman** [comment]
> dude, dont do step 1, i got it why you did like that, that's actually great. instead of 3, make the hamburger span elements to black when theme is switched

sure i will try to work with it
