### ISSUE TITLE
Component design for Login/Signup.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#3]
Wanted a component for Login and Signup pages and linking it on Navbar

**Comment by alberturria** [comment]
Hey @Abhiramborige do you mind if I take care of this?

**Comment by Abhiramborige** [comment]
Yes, best of luck !

**Comment by alberturria** [comment]
@Abhiramborige hope this is what you was looking for! :call_me_hand: Otherwise, let me know and I'll modify it accordingly.

**Comment by Abhiramborige** [comment]
Yup that's great !

**Comment by Abhiramborige** [comment]
thanks for the contrib
