### ISSUE TITLE
More characters.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#5]
We need more and more and more characters to be displayed to community !!

**Comment by khush021** [comment]
Can you assign this to me

**Comment by Abhiramborige** [comment]
Yup sure!

**Comment by NisargChokshi** [comment]
@Abhiramborige Can we update the Avatars of the Characters using this website:
[https://getavataaars.com/](https://getavataaars.com/)

**Comment by Abhiramborige** [comment]
@NisargChokshi 
No dude, dicebear micah style is fine and no need to change

**Comment by Abhiramborige** [comment]
@khush021 done ??

**Comment by Abhiramborige** [comment]
krishna
sun
jayadrata
gatotkacha
hidimbi
salwa
karna
sanjaya
sakuni
dussyasana
sanjeev
yaksha
abhimanyu
yaja
upayaja
subhadra
jarasandha
and manyy..

**Comment by khush021** [comment]
I am almost done
