### ISSUE TITLE
Need login/signup functionality.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#6]
Login, signup in the web app for storing:
1. Logged in user's favorite characters.
2. Their contribution and that to be displayed on home page of web app.
3. Their contributions to be stored in anyDB (preferably mongo or firebase)
New users to be as registered users and be able to log in.

**Comment by Tashima42** [comment]
Hi, I would like to help with the database setup

**Comment by Abhiramborige** [comment]
Yup , go ahead, mongo or firebase ?

**Comment by Tashima42** [comment]
Mongo, I already have an authentication service project that could help with the basics: https://github.com/Tashima42/authentication-service
The README is in portuguese, but the functionality is simple, the client uses a JWT for authentication, this JWT is valid for X hours, when it expires, the client uses a refresh token to get a new JWT.

**Comment by Abhiramborige** [comment]
ok cool.
you dont use sequelize here right?, you only use that repo for just JWT authentications and token stuff right?
thanks you can plz continue

**Comment by Tashima42** [comment]
Yes, the architecture is really modular, changing the database is simple.
