### ISSUE TITLE
Improving into PWA

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#7]
Let app can be installed and work offline !
Performance was degraded when app was made into basic PWA. Please help

**Comment by MeerHamza1421** [comment]
If I'm getting it right, You want when the user uses it without internet It shows an error message, Like connect to internet or internet is not connected, etc.

**Comment by Abhiramborige** [comment]
> If I'm getting it right, You want when the user uses it without internet It shows an error message, Like connect to the internet or internet is not connected, etc?

Not like that, but yes, I need this feature of getting "you are offline" message when user clicks on login, signup and connect form.
My issue is that before adding the service-worker.js, my app performance was 79% (lighthouse). But after adding the service-worker.js (same modifications as done in this video by fireshipio, https://youtu.be/sFsRylCQblw), the performance is down to 38% like that.
What happened I am not getting.

Would you like to provide the feature of "You are offline" page for the mentioned routes as above, then you are welcome. If wanted to resolve performance increment issue , then you are most welcome.

**Comment by MeerHamza1421** [comment]
Hey, Can I give the offline feature a try?

**Comment by MeerHamza1421** [comment]
Hey 👋, Just a question I'm facing a bit of difficulty while implementing offline feature with workbox. Can I replace the workbox service worker with a custom service worker? I think It also resolves the performance issue too.

**Comment by Abhiramborige** [comment]
ok, use anything until it is safer for the application
